module.exports = [
  {
    id: 65188,
    name: 'Equipment',
    href: '/directory/equipment',
    values: [
      {
        id: 65234,
        name: 'Compressed Air Systems',
        href: '/directory/equipment/compressed-air-systems',
        values: [],
      },
      {
        id: 65236,
        name: 'Jacks, Stands, and Hoists',
        href: '/directory/equipment/jacks-stands-and-hoists',
        values: [],
      },
      {
        id: 65235,
        name: 'Lifts and Lifting Equipment',
        href: '/directory/equipment/lifts-and-lifting-equipment',
        values: [],
      },
      {
        id: 65237,
        name: 'Oil, Lube, and Fluid Equipment',
        href: '/directory/equipment/oil-lube-and-fluid-equipment',
        values: [],
      },
      {
        id: 65238,
        name: 'Painting and Refinish',
        href: '/directory/equipment/painting-and-refinish',
        values: [],
      },
      {
        id: 65239,
        name: 'Shop Equipment',
        href: '/directory/equipment/shop-equipment',
        values: [
          {
            id: 65242,
            name: 'Cleaning Supplies and Equipment',
            href: '/directory/equipment/shop-equipment/cleaning-supplies-and-equipment',
            values: [],
          },
          {
            id: 65244,
            name: 'Hoses and Reels',
            href: '/directory/equipment/shop-equipment/hoses-and-reels',
            values: [],
          },
          {
            id: 65243,
            name: 'Shop Heating and Cooling Equipment',
            href: '/directory/equipment/shop-equipment/shop-heating-and-cooling-equipment',
            values: [],
          },
        ],
      },
      {
        id: 65240,
        name: 'Tire and Wheel Large Equipment',
        href: '/directory/equipment/tire-and-wheel-large-equipment',
        values: [],
      },
      {
        id: 65241,
        name: 'Tool Storage',
        href: '/directory/equipment/tool-storage',
        values: [
          {
            id: 65246,
            name: 'Tool Organizers',
            href: '/directory/equipment/tool-storage/tool-organizers',
            values: [],
          },
          {
            id: 65245,
            name: 'Toolboxes and Tool Carts',
            href: '/directory/equipment/tool-storage/toolboxes-and-tool-carts',
            values: [],
          },
          {
            id: 65247,
            name: 'Work Benches and Cabinets',
            href: '/directory/equipment/tool-storage/work-benches-and-cabinets',
            values: [],
          },
        ],
      },
    ],
  },
  {
    id: 65189,
    name: 'Parts',
    href: '/directory/parts',
    values: [
      {
        id: 65248,
        name: 'Battery / Starting / Charging Systems',
        href: '/directory/parts/battery-starting-charging-systems',
        values: [],
      },
      {
        id: 65249,
        name: 'Chassis / Suspension / Steering',
        href: '/directory/parts/chassis-suspension-steering',
        values: [],
      },
      {
        id: 65250,
        name: 'Engine and Powertrain',
        href: '/directory/parts/engine-and-powertrain',
        values: [],
      },
      {
        id: 65252,
        name: 'General Service',
        href: '/directory/parts/general-service',
        values: [],
      },
      {
        id: 65253,
        name: 'HVAC',
        href: '/directory/parts/hvac',
        values: [],
      },
      {
        id: 65251,
        name: 'Hybrid and EV Service and Repairs',
        href: '/directory/parts/hybrid-and-ev-service-and-repairs',
        values: [],
      },
    ],
  },
  {
    id: 65187,
    name: 'Tools',
    href: '/directory/tools',
    values: [
      {
        id: 65191,
        name: 'ADAS Calibration and Programming',
        href: '/directory/tools/adas-calibration-and-programming',
        values: [],
      },
      {
        id: 65192,
        name: 'Air Conditioning (A/C) Service and Repair',
        href: '/directory/tools/air-conditioning-ac-service-and-repair',
        values: [],
      },
      {
        id: 65193,
        name: 'Air Tools',
        href: '/directory/tools/air-tools',
        values: [],
      },
      {
        id: 65194,
        name: 'Body Shop and Repair',
        href: '/directory/tools/body-shop-and-repair',
        values: [],
      },
      {
        id: 65195,
        name: 'Brake Service and Tools',
        href: '/directory/tools/brake-service-and-tools',
        values: [],
      },
      {
        id: 65196,
        name: 'Chemicals',
        href: '/directory/tools/chemicals',
        values: [],
      },
      {
        id: 65197,
        name: 'Computers and Tablets',
        href: '/directory/tools/computers-and-tablets',
        values: [],
      },
      {
        id: 65198,
        name: 'Cordless Tools',
        href: '/directory/tools/cordless-tools',
        values: [
          {
            id: 65219,
            name: 'Cordless Ratchets',
            href: '/directory/tools/cordless-tools/cordless-ratchets',
            values: [],
          },
          {
            id: 65220,
            name: 'Cordless Sanders',
            href: '/directory/tools/cordless-tools/cordless-sanders',
            values: [],
          },
          {
            id: 65218,
            name: 'Cordless Wrenches',
            href: '/directory/tools/cordless-tools/cordless-wrenches',
            values: [],
          },
        ],
      },
      {
        id: 65199,
        name: 'Diagnostic Test Equipment',
        href: '/directory/tools/diagnostic-test-equipment',
        values: [
          {
            id: 65221,
            name: 'Borescopes, Videoscopes',
            href: '/directory/tools/diagnostic-test-equipment/borescopes-videoscopes',
            values: [],
          },
        ],
      },
      {
        id: 65200,
        name: 'Electrical System Tools & Equipment',
        href: '/directory/tools/electrical-system-tools-and-equipment',
        values: [
          {
            id: 65222,
            name: 'Battery Service and Testing',
            href: '/directory/tools/electrical-system-tools-and-equipment/battery-service-and-testing',
            values: [],
          },
          {
            id: 65223,
            name: 'Battery Starting and Charging',
            href: '/directory/tools/electrical-system-tools-and-equipment/battery-starting-and-charging',
            values: [],
          },
          {
            id: 65224,
            name: 'Jump Starters',
            href: '/directory/tools/electrical-system-tools-and-equipment/jump-starters',
            values: [],
          },
        ],
      },
      {
        id: 65201,
        name: 'Emissions System Tools',
        href: '/directory/tools/emissions-system-tools',
        values: [],
      },
      {
        id: 65202,
        name: 'Engine Service and Repair Tools',
        href: '/directory/tools/engine-service-and-repair-tools',
        values: [],
      },
      {
        id: 65203,
        name: 'Hand Tools',
        href: '/directory/tools/hand-tools',
        values: [
          {
            id: 65225,
            name: 'Drivers, Nut Drivers, Screwdrivers',
            href: '/directory/tools/hand-tools/drivers-nut-drivers-screwdrivers',
            values: [],
          },
          {
            id: 65226,
            name: 'Pliers',
            href: '/directory/tools/hand-tools/pliers',
            values: [],
          },
          {
            id: 65227,
            name: 'Ratchets',
            href: '/directory/tools/hand-tools/ratchets',
            values: [],
          },
          {
            id: 65228,
            name: 'Torque Wrenches',
            href: '/directory/tools/hand-tools/torque-wrenches',
            values: [],
          },
          {
            id: 65229,
            name: 'Wrenches',
            href: '/directory/tools/hand-tools/wrenches',
            values: [],
          },
        ],
      },
      {
        id: 65204,
        name: 'Hybrid and EV Service and Repairs',
        href: '/directory/tools/hybrid-and-ev-service-and-repairs',
        values: [],
      },
      {
        id: 65205,
        name: 'Inspection Tools',
        href: '/directory/tools/inspection-tools',
        values: [],
      },
      {
        id: 65206,
        name: 'Leak Detection',
        href: '/directory/tools/leak-detection',
        values: [],
      },
      {
        id: 65207,
        name: 'Lighting',
        href: '/directory/tools/lighting',
        values: [],
      },
      {
        id: 65208,
        name: 'Repair Information Sources',
        href: '/directory/tools/repair-information-sources',
        values: [],
      },
      {
        id: 65209,
        name: 'Safety Equipment & Personal Gear',
        href: '/directory/tools/safety-equipment-and-personal-gear',
        values: [
          {
            id: 65232,
            name: 'Gloves',
            href: '/directory/tools/safety-equipment-and-personal-gear/gloves',
            values: [],
          },
          {
            id: 65230,
            name: 'Knives',
            href: '/directory/tools/safety-equipment-and-personal-gear/knives',
            values: [],
          },
          {
            id: 65231,
            name: 'Safety Glasses and Eye Protection',
            href: '/directory/tools/safety-equipment-and-personal-gear/safety-glasses-and-eye-protection',
            values: [],
          },
        ],
      },
      {
        id: 65210,
        name: 'Scan tools and Scan tool accessories',
        href: '/directory/tools/scan-tools-and-scan-tool-accessories',
        values: [],
      },
      {
        id: 65211,
        name: 'Shop Management and Point of Sale',
        href: '/directory/tools/shop-management-and-point-of-sale',
        values: [],
      },
      {
        id: 65212,
        name: 'Specialty Tools',
        href: '/directory/tools/specialty-tools',
        values: [],
      },
      {
        id: 65213,
        name: 'Suspension and Steering Service Tools',
        href: '/directory/tools/suspension-and-steering-service-tools',
        values: [],
      },
      {
        id: 65214,
        name: 'Tire and Wheel Service Small Tools',
        href: '/directory/tools/tire-and-wheel-service-small-tools',
        values: [
          {
            id: 65233,
            name: 'TPMS Tools',
            href: '/directory/tools/tire-and-wheel-service-small-tools/tpms-tools',
            values: [],
          },
        ],
      },
      {
        id: 65215,
        name: 'Tool Accessories',
        href: '/directory/tools/tool-accessories',
        values: [],
      },
      {
        id: 65217,
        name: 'Top 100 Most Wanted Products',
        href: '/directory/tools/top-100-most-wanted-products',
        values: [],
      },
      {
        id: 65216,
        name: 'Welding Equipment',
        href: '/directory/tools/welding-equipment',
        values: [],
      },
    ],
  },
  {
    id: 65190,
    name: 'Training',
    href: '/directory/training',
    values: [
      {
        id: 65254,
        name: 'ASE Study and Training Products',
        href: '/directory/training/ase-study-and-training-products',
        values: [],
      },
      {
        id: 65255,
        name: 'Training Products and Tools',
        href: '/directory/training/training-products-and-tools',
        values: [],
      },
    ],
  },
];
